webtalk_init -webtalk_dir /nfs/home/b/b_mihigo/lab4_encs/lab4_encs.sim/sim_1/behav/xsim/xsim.dir/registers_min_max_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr  2 14:59:38 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174208431_1777582641_210784520_540" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0054091e-8d2c-48f1-9a75-23d48578fc4c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c7ddc693fead4be58dd45d453bcb9fb7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "36" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Scientific" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Scientific Linux release 7.9 (Nitrogen)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-12700" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1025.903 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "500 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.07_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124088_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3656505358 -regid "174208431_1777582641_210784520_540" -xml /nfs/home/b/b_mihigo/lab4_encs/lab4_encs.sim/sim_1/behav/xsim/xsim.dir/registers_min_max_behav/webtalk/usage_statistics_ext_xsim.xml -html /nfs/home/b/b_mihigo/lab4_encs/lab4_encs.sim/sim_1/behav/xsim/xsim.dir/registers_min_max_behav/webtalk/usage_statistics_ext_xsim.html -wdm /nfs/home/b/b_mihigo/lab4_encs/lab4_encs.sim/sim_1/behav/xsim/xsim.dir/registers_min_max_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
